spring:
  data:
    mongodb:
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
      database: Keep_Note_6
      port: 27017
      host: localhost
  application:
    name: note-service
server:
  port: 8082
