version: '3'
services:
  user-auth:
    image: user-auth
    build:
      context: UserAuthentication-Service/
    restart: always
    network_mode: host
    ports:
      - 8082:8082
    depends_on:
      - user-mysql

  reminder-service:
    image: reminder-app
    build:
      context: ReminderService/
    restart: always
    network_mode: host
    ports:
        - 8083:8083
    depends_on:
        - mongo-service

  note-service:
    image: note-app
    build:
      context: NoteService/
    restart: always
    network_mode: host
    ports:
      - 8084:8084
    depends_on:
      - mongo-service

  category-service:
     image: category-app
     build:
       context: CategoryService/
     restart: always
     network_mode: host
     ports:
       - 8085:8085
     depends_on:
       - mongo-service

  user-service:
     image: user-app
     build:
       context: UserService/
     restart: always
     network_mode: host
     ports:
       - 8081:8081
     depends_on:
       - mongo-service
        
        
   

  user-mysql:
    image: mysql:5.7
    restart: always
    network_mode: host
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keepnote3

  mongo-service:
      image: mongo:latest
      command: mongod
      network_mode: host
      restart: always
      volumes:
        - /data/dump:/data/db
      ports:
        - 27017:27017
        
  angular-service-frontend:
    image: angular-image
    container_name: frontend-angular
    build: ../angular-keep-level-3-assignment/
    restart: always
    network_mode: host
    ports:
    - 4200:4200